before:
  hooks:
    - make deps

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github

nfpms:
  - homepage: https://github.com/lureevar/toddo
    description: 'A simple CLI todo list application inspired by todo.txt'
    version_metadata: git
    maintainer: Luiz Felipe
    license: GPL-3.0-only
    vendor: Luiz Felipe
    formats:
    - apk
    - deb
    - rpm